name: Xenomai Pi kernel build tests

on:
  pull_request:
    paths-ignore:
      - '.github/**'
    branches: [ "rpi-*" ]
  push:
    paths-ignore:
      - '.github/**'
    branches: [ "rpi-*" ]
  workflow_dispatch:

env:
  NUM_JOBS: 3

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - name: bcm2711_arm64
            arch: arm64
            defconfig: bcm2711_defconfig
            kernel: kernel8

    steps:
    - name: Update install
      run:
        sudo apt-get update

    - name: Install toolchain
      run:
        sudo apt-get install gcc-aarch64-linux-gnu;

      timeout-minutes: 5

    - uses: actions/checkout@v3
      with:
        fetch-depth: 1
        clean: true

    - name: Build kernel ${{matrix.name}}
      run: |
        mkdir ${{github.workspace}}/build
        export ARCH=${{matrix.arch}}
        KERNEL=kernel8
        export CROSS_COMPILE=aarch64-linux-gnu-
        export DTS_SUBDIR=broadcom
        export IMAGE=Image.gz
        
        wget https://source.denx.de/Xenomai/xenomai/-/archive/v3.2.4/xenomai-v3.2.4.tar.bz2 --no-check-certificate
        tar xjvf xenomai-v3.2.4.tar.bz2
        xenomai-v3.2.4/scripts/prepare-kernel.sh  --arch=arm64 --linux=./
        KERNEL=kernel8
        make ARCH=arm64 CROSS_COMPILE=aarch64-linux-gnu- bcm2711_defconfig
        make ARCH=arm64 CROSS_COMPILE=aarch64-linux-gnu- Image modules dtbs -j 24

    - name: Tar build
      run: tar -cvf ${{matrix.name}}_build.tar -C ${{github.workspace}}/install .

    - name: Upload results
      uses: actions/upload-artifact@v3
      with:
        name: ${{matrix.name}}_build
        path: ${{matrix.name}}_build.tar
        retention-days: 90
